### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [MarcinLebiecki/BDOT10k_GML_SHP#1]
# Problem

Please remove the _pycache folder it's generated on install.

The browser, data source manager, processing already do import data. How different is this functionality than the one already in core

**Comment by MarcinLebiecki** [comment]
Dear NyakudyaA,
Thank you for your comments. I deleted _pycache folder and uploaded changed plugin again.
Main functionality for my plugin is to symbolize layers to be similar to topographic maps 1:10 000 from BDOT10k database. Plugin creates layer, changes layer's names, adds symbolization (adds QML files), adds attributes when importing GML files by adding GFS files, adds SVG library to symbolize point objects, creates joins when importing GML files.

<img width="1440" alt="Zrzut ekranu 2020-05-25 o 10 37 20" src="https://user-images.githubusercontent.com/65350186/82795153-de866a00-9e73-11ea-85ed-4ba02e53bcdb.png">

Best regards,
Marcin Lebiecki

**Comment by NyakudyaA** [comment]
@MarcinLebiecki Can you also remove the zipped files in the repo. This will make the uploaded plugin smaller

**Comment by MarcinLebiecki** [comment]
Dear NyakudyaA,
Zipped files are importent. I have to zip files because when I tried to upload to github I had information: "Yowza, that’s a lot of files. Try again with fewer than 100 files."

Best regards,
Marcin Lebiecki

**Comment by NyakudyaA** [comment]
> Dear NyakudyaA,
> Zipped files are importent. I have to zip files because when I tried to upload to github I had information: "Yowza, that’s a lot of files. Try again with fewer than 100 files."
> 
> Best regards,
> Marcin Lebiecki

Does the plugin use any zipped files ?

**Comment by MarcinLebiecki** [comment]
Dear NyakudyaA,
Plugin has got folders with QML, SVG and GFS files. Zipped files exists only in github. Normally there should be folders with files.

Best regards,
Marcin Lebiecki
