### ISSUE TITLE
File not found 

### ISSUE THREAD

**Issue by PawelKra** [MarcinLebiecki/BDOT10k_GML_SHP#2]
Dear MarcinLebiecki

Please fix FileNotFoundError while try to abort pointing gml file 
(/BDOT10k_GML_SHP_loader.py", line 582,)

Best Regards
PK

**Comment by MarcinLebiecki** [comment]
> Dear MarcinLebiecki
> Please fix FileNotFoundError while try to abort pointing gml file
> (/BDOT10k_GML_SHP_loader.py", line 582,)
> Best Regards
> PK

Thank you for issue. I fixed it and new version is ready to download.
