### ISSUE TITLE
Plik OT_BUZM_L.gfs nie jest wykorzystywany przy parsowaniu danych

### ISSUE THREAD

**Issue by p0cisk** [MarcinLebiecki/BDOT10k_GML_SHP#5]
Plik `OT_BUZM_L.gfs` jest w repozytorium, ale nie jest wykorzystywany podczas parsowania przez co niektóre informacje nie są dodawane w tabeli atrybutów np. `ciek3` czy `zbiornikWodny2`

**Comment by MarcinLebiecki** [comment]
Nowa wersja wtyczki nie wykorzystuje już plików gfs.
