### ISSUE TITLE
BDOT10k_GML_SHP 2.01

### ISSUE THREAD

**Issue by Mariusz234msk** [MarcinLebiecki/BDOT10k_GML_SHP#6]
Wtyczka nie działa poprawnie. Niby wczytuje zbiory danych ale albo ich nie pokazuje w ogóle (zbiory gml) albo wybiórczo (shp)

**Comment by MarcinLebiecki** [comment]
Proszę o wskazanie wersji QGIS jaka została użyta oraz teryt powiatu danych BDOT10k, które były wczytywane.

**Comment by Mariusz234msk** [comment]
Wersja qgis 3.28. Ale i 3.22 efekt był taki sam (tzn. niby zbiór załadowany, ale niewidoczny w oknie mapy). Ładować próbowałem dane z różnych powiatów z woj. opolskiego i z lubuskiego i z zachodniopomorskiego. Musiałem wrócić do wtyczki v 1.05 i wszystko zaczęło działać.   Pozdrawiam  Mariusz   
     
      
       
        Dnia 05 kwietnia 2024 14:49 MarcinLebiecki ***@***.***&gt; napisał(a):
       
    
       
         
 Proszę o wskazanie wersji QGIS jaka została użyta oraz teryt powiatu danych BDOT10k, które były wczytywane.

**Comment by MarcinLebiecki** [comment]
Nowa wersja wtyczki od wersji 2.0.0 wczytuje dane BDOT10k tylko w nowym modelu danych. Do wczytywania BDOT10k w starym modelu danych należy użyć wtyczki w wersji 1.0.8
